Add support Lenovo snowman 1080p camera
OpenIPC/builder pull request #13
Opened 2024-02-10 10:59 UTC by githubtmp7

u-boot stock password lenovoipcsm2ubp
required  patched u-boot https://github.com/OpenIPC/firmware/issues/695#issuecomment-1925399400

2024-02-11 11:48 UTC, FlyRouter reviewed
Thank you very much for your work.
However, a series of changes and improvements to your PR are required.
We will move step by step.

2024-02-11 12:07 UTC, FlyRouter requested changes
Need many changes for sync work

2024-02-11 17:03 UTC, FlyRouter commented on devices/hi3518ev200_ultimate_lenovo-snowman-1080p/general/scripts/excludes/hi3518ev200_ultimate.list
Where did the removal of unnecessary kernel modules go?

2024-02-11 17:06 UTC, FlyRouter commented on devices/hi3518ev200_ultimate_lenovo-snowman-1080p/general/overlay/usr/share/openipc/customizer.sh
Необходимо проверить работу без указания сенсора, что-бы работал автодетект.
Тип прошивки нужно изменить на Lite

2024-02-12 09:10 UTC, githubtmp7 commented on devices/hi3518ev200_ultimate_lenovo-snowman-1080p/general/overlay/usr/share/openipc/customizer.sh
Автодетект работает, зачем изменять тип прошивки на lite?
Если уж так необходим Lite можно сделать в дополнение.

2024-02-12 09:14 UTC, githubtmp7 commented on devices/hi3518ev200_ultimate_lenovo-snowman-1080p/general/scripts/excludes/hi3518ev200_ultimate.list
В настройках ядра отключены ненужные модули, удалять особо нечего.

2024-02-15 09:36 UTC, merged